classdef Parameters
    properties
        Wh
        RotorNo
        Coaxial
        useWheelbase
        Wheelbase
        useOverlap
        Overlap
        PropDiameter_Min
        PropDiameter_Max
        SelectBattCellNo
        BattCellNo_Desired
        mass_NoDrive_Est
        mass_NoDrive_NoPayload_Est
        mass_Combo_Est
        DisplayResults
        ThrustWeightRatio
        OptimizationGoal
    end
end